// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int nTimes = Integer.parseInt(args[0]);
		int overFive = 0;
		int underFive = 0;
		double randomSum = 0;

		for (int i = 0; i != nTimes; i++) {
			double random = Math.random();
			randomSum += random;
			if (random <= 0.5) {
				underFive++;
			} else {
				overFive++;
			}
			//System.out.println(random);
		}

		System.out.println("> 0.5: " + overFive + " times");
		System.out.println("<= 0.5: " + underFive + " times");
		System.out.println("Ratio: " + randomSum / nTimes);

	}
}
